name: Build and Release Electron App

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm run make -- --platform=linux
      - uses: actions/upload-artifact@v4
        with:
          name: linux-packages
          path: out/make/

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm run make -- --platform=win32
      - uses: actions/upload-artifact@v4
        with:
          name: windows-packages
          path: out/make/

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm run make -- --platform=darwin
      - uses: actions/upload-artifact@v4
        with:
          name: macos-packages
          path: out/make/

  release:
    needs: [build-linux, build-windows, build-macos]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Git Tag
        id: tag
        run: |
          TAG="v$(date +%Y.%m.%d)"
          echo "TAG=$TAG" >> $GITHUB_OUTPUT
          git tag $TAG
          git push origin $TAG
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.TAG }}
          files: |
            out/make/*.exe
            out/make/*.dmg
            out/make/*.deb